name: uiux_portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  visibility_detector: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Make sure these folders & files exist and the names match exactly.
  assets:
    - assets/certs/
    # or, if you prefer to be explicit instead of using the whole folder:
    # - assets/resforce_ui.png
    # - assets/epass_ui.png
    # - assets/stockup_ui.png
    # - assets/pawcentral_ui.png
    # - assets/design_dashboard.png
    # - assets/design_onboarding.png
    # - assets/design_landing.png
    # - assets/design_poster.png
    # - assets/certs/it_specialist_html_css.png
    # - assets/certs/ccna_intro_networks.png
    # - assets/certs/unesco_hackathon_delegate.png
    # - assets/certs/nextgenph_delegate.png
